server:
  port: 8090

# springboot项目配置
spring:
  application:
    name: koj-service
  profiles:
    active: druid
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 172.25.34.148
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 1234
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  rabbitmq:
    host: xxx
    username: root
    password: 1234
    # 能者多劳，防止能者空闲等待
    listener:
      simple:
        prefetch: 1
  # 邮箱配置
  mail:
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: kkkylen@qq.com
    #授权码
    password: xxx
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
# mybatis plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

# sa-token配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: koj
  # token 有效期（单位：秒） 默认30天（2592000），-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 2592000
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# knife4j接口文档配置
knife4j:
  enable: true
  openapi:
    title: Knife4j文档
    description: Knife4j接口文档
    email: kkkylen@qq.com
    concat: KyLen
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - fun.kylen.koj.controller

# oauth2配置
oauth2:
  github-client-id: xxx
  github-secret: xxx
