/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/components/DefaultLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tiny: typeof import('@opentiny/vue')['default']
    TinyAlert: typeof import('@opentiny/vue')['Alert']
    TinyBadge: typeof import('@opentiny/vue')['Badge']
    TinyButton: typeof import('@opentiny/vue')['Button']
    TinyCard: typeof import('@opentiny/vue')['Card']
    TinyCol: typeof import('@opentiny/vue')['Col']
    TinyDivider: typeof import('@opentiny/vue')['Divider']
    TinyGrid: typeof import('@opentiny/vue')['Grid']
    TinyGridColumn: typeof import('@opentiny/vue')['GridColumn']
    TinyImage: typeof import('@opentiny/vue')['Image']
    TinyLay: typeof import('@opentiny/vue')['Lay']
    TinyLayout: typeof import('@opentiny/vue')['Layout']
    TinyNavMenu: typeof import('@opentiny/vue')['NavMenu']
    TinyRow: typeof import('@opentiny/vue')['Row']
    TinySearch: typeof import('@opentiny/vue')['Search']
    TinySticky: typeof import('@opentiny/vue')['Sticky']
    TinyUserHead: typeof import('@opentiny/vue')['UserHead']
  }
}
